// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import AlertController from './alert_controller.js';
application.register('alert', AlertController);

// import DragController from './drag_controller.js';
// application.register('drag', DragController);

import HelloController from './hello_controller.js';
application.register('hello', HelloController);

import TrixMarkController from './trix_mark_controller.js';
application.register('trix-mark', TrixMarkController);

import ReadMore from 'stimulus-read-more';
application.register('read-more', ReadMore);

// import DraggableController from './draggable_controller';
// application.register('draggable', DraggableController);
